import pc from "picocolors";
import type { RuntimeOptions } from "../../config/index.ts";
import { createEngine, getPlugin } from "../../engines/index.ts";
import type { AIEngineName, AIResult } from "../../engines/types.ts";
import {
	OpencodeServerExecutor,
	PortManager,
	displayTmuxModeHeader,
	displayAttachInstructions,
	displayTmuxCompletionSummary,
	getMessageOptionsForPhase,
	type ServerInfo,
} from "../../engines/opencode/index.ts";
import { TmuxSessionManager, ensureTmuxInstalled, getInstallationInstructions } from "../../engines/tmux/index.ts";
import { saveIssuesForRun } from "../../state/issues.ts";
import {
	syncLegacyPlansView,
	writeProblemBriefForRun,
} from "../../state/plan-store.ts";
import { initializeDir } from "../../state/manager.ts";
import {
	createRun,
	updateRunPhaseInMeta,
	updateRunStats,
} from "../../state/runs.ts";
import { buildLeadInvestigatorPrompt as buildLIPromptFromAgent } from "../../agents/lead-investigator.ts";
import { AGENT_ROLES, type Issue, type Severity } from "../../state/types.ts";
import {
	formatDuration,
	formatTokens,
	logDebug,
	logError,
	logInfo,
	logSuccess,
	logWarn,
	setVerbose,
} from "../../ui/logger.ts";
import { ProgressSpinner } from "../../ui/spinners.ts";
import { extractJsonFromResponse } from "../../utils/json-extractor.ts";

/**
 * Result of scanning for work items
 */
interface ScanResult {
	success: boolean;
	issuesFound: number;
	inputTokens: number;
	outputTokens: number;
	problemBriefPath?: string;
	error?: string;
	/** The run ID created by this scan - used by pipeline to ensure subsequent phases use the same run */
	runId?: string;
}

/**
 * Parsed work item from AI response
 */
interface ParsedIssue {
	type?: string;
	title?: string;
	rationale?: string;
	symptom?: string;
	hypothesis?: string;
	severity: Severity;
	frequency?: string;
	blast_radius?: string;
	scope_impact?: string;
	strategy?: string;
}

/**
 * Build the Lead Investigator prompt.
 * Delegates to the agent module's prompt builder for single source of truth.
 */
function buildLeadInvestigatorPrompt(workDir: string, scanFocus?: string): string {
	return buildLIPromptFromAgent(workDir, {
		scope: scanFocus ? [scanFocus] : undefined,
	});
}


/**
 * Parse issues from AI response
 */
function parseIssuesFromResponse(response: string): ParsedIssue[] {
	// Extract JSON from response using robust multi-strategy extraction
	const jsonStr = extractJsonFromResponse(response);
	if (!jsonStr) {
		logDebug("Failed to extract JSON from scan response");
		return [];
	}

	try {
		const parsed = JSON.parse(jsonStr);

		if (!Array.isArray(parsed)) {
			logWarn("AI response is not an array, wrapping in array");
			return [parsed].filter(isValidParsedIssue);
		}

		return parsed.filter(isValidParsedIssue);
	} catch (error) {
		logDebug("Failed to parse JSON response:", error);

		// Try to find JSON array in the response
		const arrayMatch = response.match(/\[\s*\{[\s\S]*?\}\s*\]/);
		if (arrayMatch) {
			try {
				const parsed = JSON.parse(arrayMatch[0]);
				return parsed.filter(isValidParsedIssue);
			} catch {
				// Fall through
			}
		}

		return [];
	}
}

/**
 * Validate parsed work item has required fields.
 * Accepts both new format (title/rationale) and legacy format (symptom/hypothesis).
 */
function isValidParsedIssue(issue: unknown): issue is ParsedIssue {
	if (typeof issue !== "object" || issue === null) {
		return false;
	}

	const obj = issue as Record<string, unknown>;

	// Accept new format (title/rationale) or legacy format (symptom/hypothesis)
	const hasTitle = typeof obj.title === "string" && obj.title.trim() !== "";
	const hasSymptom = typeof obj.symptom === "string" && obj.symptom.trim() !== "";
	if (!hasTitle && !hasSymptom) {
		return false;
	}

	const hasRationale = typeof obj.rationale === "string" && obj.rationale.trim() !== "";
	const hasHypothesis = typeof obj.hypothesis === "string" && obj.hypothesis.trim() !== "";
	if (!hasRationale && !hasHypothesis) {
		return false;
	}

	const validSeverities = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];
	if (typeof obj.severity !== "string" || !validSeverities.includes(obj.severity)) {
		// Default to MEDIUM if invalid
		obj.severity = "MEDIUM";
	}

	return true;
}

/**
 * Generate Work Brief markdown
 */
function generateWorkBrief(issues: Issue[], runId: string): string {
	const timestamp = new Date().toISOString();
	const parts: string[] = [];

	parts.push(`# Work Brief v0

> **Status**: UNVALIDATED
> **Run ID**: ${runId}
> **Generated**: ${timestamp}
> **Work Items Found**: ${issues.length}

---

## Overview

This Work Brief was generated by the Lead Investigator (LI) agent during the scan phase.
All work items are currently **UNVALIDATED** and require validation before planning.

---

## Work Items
`);

	if (issues.length === 0) {
		parts.push("No significant work items were identified during the scan.\n");
	} else {
		for (const issue of issues) {
			const title = issue.title ?? issue.symptom;
			const rationale = issue.rationale ?? issue.hypothesis;
			const itemType = issue.type ?? "bug";
			parts.push(`### ${issue.id}: ${title}

| Field | Value |
|-------|-------|
| **Type** | ${itemType} |
| **Status** | ${issue.status} |
| **Severity** | ${issue.severity} |
| **Rationale** | ${rationale} |
${issue.scope_impact ? `| **Scope Impact** | ${issue.scope_impact} |` : ""}
${issue.frequency ? `| **Frequency** | ${issue.frequency} |` : ""}
${issue.blast_radius ? `| **Blast Radius** | ${issue.blast_radius} |` : ""}
${issue.strategy ? `| **Strategy** | ${issue.strategy} |` : ""}
| **Created** | ${issue.created_at} |

---
`);
		}
	}

	parts.push(`## Next Steps

1. Run \`milhouse validate\` to validate each work item with evidence
2. Work items will be marked as CONFIRMED, FALSE, PARTIAL, or MISDIAGNOSED
3. Run \`milhouse plan\` to generate WBS for confirmed work items
`);

	return parts.join("\n");
}

/**
 * Run the scan command - Lead Investigator agent
 *
 * Creates Work Brief v0 (UNVALIDATED) by analyzing the repository
 * for work items (bugs, features, refactoring, improvements, tasks).
 *
 * IMPORTANT: Each scan creates a NEW run with isolated state.
 */
export async function runScan(options: RuntimeOptions): Promise<ScanResult> {
	const workDir = process.cwd();
	const startTime = Date.now();

	// Set verbose mode
	setVerbose(options.verbose);

	// Initialize milhouse directory if needed
	initializeDir(workDir);

	// Create a NEW run for this scan
	// This is the key change - each scan creates isolated state
	const runMeta = createRun({
		scope: options.scanFocus,
		workDir,
	});

	logInfo(`Created new run: ${pc.cyan(runMeta.id)}`);
	if (options.scanFocus) {
		logInfo(`Scope: ${pc.dim(options.scanFocus)}`);
	}

	// Update phase to scanning
	updateRunPhaseInMeta(runMeta.id, "scan", workDir);

	// Check engine availability
	const engine = await createEngine(options.aiEngine as AIEngineName);
	let available = false;
	try {
		const plugin = getPlugin(options.aiEngine as AIEngineName);
		available = await plugin.isAvailable();
	} catch {
		available = false;
	}

	if (!available) {
		logError(`${engine.name} CLI not found. Make sure '${engine.cliCommand}' is in your PATH.`);
		return {
			success: false,
			issuesFound: 0,
			inputTokens: 0,
			outputTokens: 0,
			error: `${engine.name} not available`,
			runId: runMeta.id,
		};
	}

	logInfo(`Starting scan with ${engine.name} (engine: ${options.aiEngine})`);
	logInfo(`Role: ${AGENT_ROLES.LI}`);
	if (options.scanFocus) {
		logInfo(`Focus: ${options.scanFocus}`);
	}

	// ============================================================================
	// TMUX MODE CHECK: Validate tmux mode requirements
	// ============================================================================
	let tmuxManager: TmuxSessionManager | null = null;
	let tmuxEnabled = false;
	let opencodeExecutor: OpencodeServerExecutor | null = null;

	if (options.tmux) {
		// Check if using OpenCode engine (tmux mode only works with OpenCode)
		if (options.aiEngine !== "opencode") {
			logWarn("Tmux mode is only supported with --opencode engine. Falling back to standard execution.");
		} else {
			// Try to ensure tmux is installed (with auto-install if possible)
			const tmuxResult = await ensureTmuxInstalled({ autoInstall: true, verbose: true });
			
			if (!tmuxResult.installed) {
				// Installation failed or not possible (e.g., Windows)
				logWarn("tmux is not available and could not be installed automatically.");
				if (tmuxResult.error) {
					logInfo(tmuxResult.error);
				}
				logInfo("Falling back to standard execution.");
				logInfo("");
				logInfo(getInstallationInstructions());
			} else {
				// tmux is available (either was already installed or just installed)
				if (tmuxResult.installedNow) {
					logSuccess(`tmux ${tmuxResult.version ?? "unknown"} was installed successfully via ${tmuxResult.method}`);
				} else {
					logDebug(`tmux ${tmuxResult.version ?? "unknown"} is already installed`);
				}
				
				// Initialize tmux manager
				tmuxManager = new TmuxSessionManager({
					sessionPrefix: "milhouse",
					verbose: options.verbose,
				});
				tmuxEnabled = true;
				logInfo("Tmux mode enabled - OpenCode server will be started with TUI attachment");
			}
		}
	}

	console.log("");

	// Build the Lead Investigator prompt
	const prompt = buildLeadInvestigatorPrompt(workDir, options.scanFocus);
	logDebug("Prompt built:", `${prompt.slice(0, 200)}...`);

	// Create progress spinner
	const spinner = new ProgressSpinner("Scanning repository", ["LI"]);

	// Execute the scan
	let result: AIResult;
	try {
		// ============================================================================
		// EXECUTION: Choose between tmux mode and standard mode
		// ============================================================================
		if (tmuxEnabled && tmuxManager) {
			// TMUX MODE: Use OpenCode server with tmux session
			logDebug("Executing scan in tmux mode");
			spinner.updateStep("Starting OpenCode server");

			opencodeExecutor = new OpencodeServerExecutor({
				autoInstall: options.autoInstall ?? true,
				verbose: options.verbose,
			});

			// Start the OpenCode server
			const port = await opencodeExecutor.startServer(workDir);
			const url = `http://localhost:${port}`;

			// Create the session FIRST via the API so we have the session ID
			const session = await opencodeExecutor.createSession({
				title: `Milhouse Scan: ${runMeta.id}`,
			});

			// Create tmux session with opencode attach, including the session ID
			const tmuxSessionBaseName = `scan-${runMeta.id.slice(0, 8)}`;
			const sessionName = tmuxManager.buildSessionName(tmuxSessionBaseName);
			const attachCmd = `opencode attach ${url} -s ${session.id}`;

			// Kill existing session if it exists (handles retry case)
			await tmuxManager.killSessionIfExists(tmuxSessionBaseName);

			const tmuxResult = await tmuxManager.createSession({
				name: tmuxSessionBaseName,
				command: attachCmd,
				workDir,
			});

			if (!tmuxResult.success) {
				logWarn(`Failed to create tmux session: ${tmuxResult.error}`);
			}

			// Display tmux mode header and attach instructions
			displayTmuxModeHeader();
			const serverInfo: ServerInfo = {
				issueId: `scan-${runMeta.id.slice(0, 8)}`,
				port,
				sessionName,
				status: "running",
				url,
			};
			displayAttachInstructions([serverInfo]);
			console.log("");

			spinner.updateStep("Executing scan via OpenCode server");

			// Send the prompt and wait for completion
			// Use autonomy config to prevent questions and restrict to read-only tools
			const response = await opencodeExecutor.sendMessage(
				session.id,
				prompt,
				getMessageOptionsForPhase("scan", options.modelOverride)
			);

			// Calculate tokens from response
			const inputTokens = response.info.inputTokens ?? 0;
			const outputTokens = response.info.outputTokens ?? 0;

			// Extract text from response parts
			const responseText = response.parts
				.filter((p) => p.type === "text")
				.map((p) => (p as { type: "text"; text: string }).text)
				.join("");

			result = {
				success: true,
				response: responseText,
				inputTokens,
				outputTokens,
			};

			// Display completion summary
			const completedServerInfo: ServerInfo = {
				...serverInfo,
				status: "completed",
			};
			displayTmuxCompletionSummary([completedServerInfo]);

			// Cleanup: Stop the server but keep tmux session for inspection
			logInfo("Stopping OpenCode server (tmux session preserved for inspection)");
			await opencodeExecutor.stopServer();
			PortManager.releaseAllPorts();
		} else {
			// STANDARD MODE: Use engine.execute directly
			if (engine.executeStreaming) {
				result = await engine.executeStreaming(
					prompt,
					workDir,
					(step) => {
						// Handle both DetailedStep and string (legacy fallback)
						if (step) {
							spinner.updateStep(step);
						} else {
							spinner.updateStep("Analyzing");
						}
					},
					{ modelOverride: options.modelOverride },
				);
			} else {
				spinner.updateStep("Executing");
				result = await engine.execute(prompt, workDir, {
					modelOverride: options.modelOverride,
				});
			}
		}
	} catch (error) {
		spinner.error("Scan failed");
		const errorMsg = error instanceof Error ? error.message : String(error);
		logError("Scan execution failed:", errorMsg);

		// Cleanup tmux resources on error
		if (opencodeExecutor) {
			try {
				await opencodeExecutor.stopServer();
				PortManager.releaseAllPorts();
			} catch {
				// Ignore cleanup errors
			}
		}

		// Update run state to failed
		updateRunPhaseInMeta(runMeta.id, "failed", workDir);

		return {
			success: false,
			issuesFound: 0,
			inputTokens: 0,
			outputTokens: 0,
			error: errorMsg,
			runId: runMeta.id,
		};
	}

	if (!result.success) {
		spinner.error("Scan failed");
		logError("Scan failed:", result.error || "Unknown error");

		// Cleanup tmux resources on error
		if (opencodeExecutor) {
			try {
				await opencodeExecutor.stopServer();
				PortManager.releaseAllPorts();
			} catch {
				// Ignore cleanup errors
			}
		}

		// Update run state to failed
		updateRunPhaseInMeta(runMeta.id, "failed", workDir);

		return {
			success: false,
			issuesFound: 0,
			inputTokens: result.inputTokens,
			outputTokens: result.outputTokens,
			error: result.error,
			runId: runMeta.id,
		};
	}

	spinner.updateStep("Parsing results");

	// Parse issues from response
	const parsedIssues = parseIssuesFromResponse(result.response);
	logDebug(`Parsed ${parsedIssues.length} issues from response`);

	// Build issues with proper IDs and save to run-specific state directory
	const savedIssues: Issue[] = [];
	const now = new Date().toISOString();

	for (const parsed of parsedIssues) {
		const timestamp = Date.now().toString(36);
		const random = Math.random().toString(36).substring(2, 8);

		// Support both new format (title/rationale) and legacy (symptom/hypothesis)
		const title = parsed.title ?? parsed.symptom ?? "";
		const rationale = parsed.rationale ?? parsed.hypothesis ?? "";
		const validTypes = ["bug", "feature", "refactor", "improvement", "task"];
		const itemType = parsed.type && validTypes.includes(parsed.type) ? parsed.type : "bug";

		const issue: Issue = {
			id: `P-${timestamp}-${random}`,
			type: itemType as Issue["type"],
			title,
			rationale,
			symptom: title,
			hypothesis: rationale,
			severity: parsed.severity,
			frequency: parsed.frequency,
			blast_radius: parsed.blast_radius,
			scope_impact: parsed.scope_impact,
			strategy: parsed.strategy,
			status: "UNVALIDATED",
			evidence: [],
			related_task_ids: [],
			created_at: now,
			updated_at: now,
		};
		savedIssues.push(issue);
	}

	// Save issues to the run's state directory using run-aware function
	saveIssuesForRun(runMeta.id, savedIssues, workDir);

	// Generate Work Brief using PlanStore (run-aware)
	const workBriefContent = generateWorkBrief(savedIssues, runMeta.id);
	const problemBriefPath = writeProblemBriefForRun(workDir, runMeta.id, workBriefContent);
	logDebug(`Work Brief written to: ${problemBriefPath}`);

	// Sync legacy plans view for backward compatibility
	syncLegacyPlansView(workDir);
	logDebug("Legacy plans view synced");

	// Update run metadata with stats
	updateRunStats(runMeta.id, { issues_found: savedIssues.length }, workDir);
	const finalPhase = savedIssues.length > 0 ? "validate" : "completed";
	updateRunPhaseInMeta(runMeta.id, finalPhase, workDir);

	const duration = Date.now() - startTime;
	spinner.success(`Scan complete ${formatTokens(result.inputTokens, result.outputTokens)}`);

	// Summary
	console.log("");
	console.log("=".repeat(50));
	logInfo("Scan Summary:");
	console.log(`  Run:           ${pc.cyan(runMeta.id)}`);
	console.log(`  Items found:   ${pc.cyan(String(savedIssues.length))}`);
	console.log(`  Duration:      ${formatDuration(duration)}`);
	console.log(`  Work Brief:    ${pc.cyan(problemBriefPath)}`);
	console.log("=".repeat(50));

	if (savedIssues.length > 0) {
		console.log("");
		logInfo("Work Items (UNVALIDATED):");
		for (const issue of savedIssues) {
			const severityColor =
				issue.severity === "CRITICAL"
					? pc.red
					: issue.severity === "HIGH"
						? pc.yellow
						: issue.severity === "MEDIUM"
							? pc.blue
							: pc.dim;
			const title = issue.title ?? issue.symptom;
			const typeTag = issue.type ? `[${issue.type}]` : "[bug]";
			console.log(`  ${pc.cyan(issue.id)} ${pc.dim(typeTag)} [${severityColor(issue.severity)}] ${title}`);
		}
		console.log("");
		logSuccess(`Run ${pc.cyan("milhouse --validate")} to validate work items`);
	} else {
		console.log("");
		logSuccess("No significant work items found in the repository");
	}

	return {
		success: true,
		issuesFound: savedIssues.length,
		inputTokens: result.inputTokens,
		outputTokens: result.outputTokens,
		problemBriefPath,
		runId: runMeta.id,
	};
}
